export const initialAppState = {
  currentView: "home",
  selectedUnit: null,
  program: null,
  entryRequirements: [],
  units: [],
  careers: [],
  announcements: [],
  bookmarks: [],
  searchTerm: "",
  yearFilter: "All",
  semesterFilter: "All",
  admin: null,
  loading: false,
  error: "",
};
